apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: nodejs-express-test
build:
  artifacts:
  - image: underdogdevops/express-test
    docker:
      dockerfile: Dockerfile
test:
  - context: .
    image: underdogdevops/express-test
    custom:
      - command: npm run test
deploy:
  kubectl:
    manifests:
    - manifests.yaml
